// Prompt Pulse — typed access to the scrubbed public dataset.
//
// Generated by GEOResearch/08_prompt_pulse/builder/make_public.py. Public-safe
// only: prompt text, Demand tier (High/Med/Low band), a direction-only trend
// (no %, no absolute volume), topic/intent/persona/stage tags, and a 0..1
// sparkline. `ppds` is kept for sorting and is never displayed; trend shows a
// normalized, capped % (or New / —).
import data from "@/content/promptPulse.json";

export type PromptTrend = { label: string; pct: number | null };

export type PromptRow = {
  prompt: string;
  topic: string;
  intent: string;
  persona: string;
  stage: string;
  ppds: number;        // internal: sort only
  demandTier: string;  // High | Medium | Low
  trend: PromptTrend;
  spark: number[];
};

export type VerticalData = {
  vertical: string;
  slug: string;
  short: string;
  label: string;
  blurb: string;
  updated: string;
  stats: {
    prompts: number; rising: number; cooling: number; decision: number;
    tiers?: { High: number; Medium: number; Low: number };
  };
  categories: { topics: string[]; intents: string[]; personas: string[]; stages: string[] };
  prompts: PromptRow[];
};

export type PromptPulseData = { updated: string; note: string; verticals: VerticalData[] };

export const promptPulse = data as PromptPulseData;
export const verticals = promptPulse.verticals;
export const getVertical = (slug?: string): VerticalData | undefined =>
  verticals.find((v) => v.slug === slug);

export const ACCENT = "hsl(195 90% 55%)";
export const GOLD = "hsl(40 85% 55%)";
const MUTED = "hsl(0 0% 55%)";

export const trendColor = (label: string): string =>
  label === "Rising"
    ? "hsl(142 70% 45%)"
    : label === "New"
      ? "hsl(265 80% 66%)"
      : label === "Cooling"
        ? "hsl(18 85% 58%)"
        : MUTED;

export const trendArrow = (label: string): string =>
  label === "Rising" ? "▲" : label === "New" ? "✦" : label === "Cooling" ? "▼" : label === "Stable" ? "▪" : "";

export const stageColor = (s: string): string =>
  s === "Decision" ? GOLD : s === "Consideration" ? ACCENT : "hsl(215 60% 62%)";

export const tierColor = (t: string): string =>
  t === "High" ? ACCENT : t === "Medium" ? GOLD : MUTED;

/** Normalized trend number for display (capped at +300%+). New / — have no %. */
export const fmtTrend = (t: PromptTrend): string => {
  if (t.label === "—") return "—";
  if (t.label === "New") return "New";
  if (t.pct == null) return t.label;
  if (t.pct > 300) return "+300%+";
  return `${t.pct > 0 ? "+" : ""}${t.pct}%`;
};

/** Sort key for trend (New ranks above big risers; — at the bottom). */
export const trendSort = (t: PromptTrend): number =>
  t.pct != null ? t.pct : t.label === "New" ? 999 : -999;

const RISING = new Set(["Rising", "New"]);

/** One-line, data-driven summary for a vertical page hero (no %). */
export function verticalTldr(v: VerticalData): string {
  const ps = v.prompts;
  if (!ps.length) return "";
  const top = ps[0].prompt;
  const risers = ps
    .filter((p) => RISING.has(p.trend.label))
    .sort((a, b) => trendSort(b.trend) - trendSort(a.trend))
    .slice(0, 2);
  const parts = [`The single highest-demand question is “${top}”.`];
  if (risers.length) parts.push(`Heating up: ${risers.map((p) => `“${p.prompt}”`).join(", ")}.`);
  parts.push(`${v.stats.decision} are purchase-ready (decision-stage) prompts.`);
  return parts.join(" ");
}

/** Cross-vertical rising/new prompts for the hub leaderboard, ranked by
 *  the normalized trend % (New ranks highest). */
export function risingAcrossVerticals(limit = 12, perVertical = 2) {
  // Representative cross-industry sample: take each vertical's strongest risers
  // (≤perVertical), then round-robin so the table isn't dominated by one industry.
  const groups = verticals.map((v) =>
    v.prompts
      .filter((p) => RISING.has(p.trend.label))
      .map((p) => ({ ...p, vShort: v.short, vSlug: v.slug }))
      .sort((a, b) => trendSort(b.trend) - trendSort(a.trend))
      .slice(0, perVertical),
  );
  const out = [] as (typeof groups)[number];
  for (let i = 0; i < perVertical && out.length < limit; i++) {
    for (const g of groups) {
      if (g[i] && out.length < limit) out.push(g[i]);
    }
  }
  return out;
}
